In [1]:
from pytorch_metric_learning.utils import common_functions as c_f


/home/lin/miniconda3/envs/apkencoder/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
y_train = [5, 2, 3, 4, 5, 1]
labels_to_indices = c_f.get_labels_to_indices(y_train)
labels_to_indices

defaultdict(list,
            {5: array([0, 4]),
             2: array([1]),
             3: array([2]),
             4: array([3]),
             1: array([5])})

In [9]:
labels_to_indices[1]

array([5])

In [10]:
5 // 2

2

In [14]:
import torch
torch.arange(5).contiguous().view(-1, 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [20]:
# one hot

a = torch.ones(8, 1)
b = torch.zero(8, 1)
print(a)
a = a[:,1].view(-1, 1)
a


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])